services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: water_gas_meter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: water_gas_meter_db
    command: ["./wait-for-it.sh", "db", "5432", "yarn", "start"]

volumes:
  postgres_data:
